feat: distinct
molgenis/ds-tidyverse-client pull request #66
Opened 2024-09-11 14:26 UTC by timcadman

## Checklist for developing new functions
- [x] Write clientside function
- [x] Write serverside function
- [x] Evaluate whether additional disclosure checks are required, and if so write them
- [x] Update .circleci/config.yml so that CI installs 'molgenis/tidyverse' from corresponding branch
- [x] Add serverside function to inst/DATASHIELD file
- [x] On clientside package run `devtools::check()`. Review and fix any broken tests. 
- [x] On serverside package run `devtools::check()`. Review and fix any broken tests. 
- [x] Add new clientside tests to 'tests/testthat'
- [x] Add new serverside tests to 'tests/testthat'
- [x] Update clientside README.md to list function as included 
- [x] Update clientside vignette with example(s) of new function use
- [x] Check clientside function documentation is correct and complete
- [x] Check serverside function documentation is correct and complete
- [x] On clientside package run `devtools::check()` and `devtools::build_site()`
- [x] On serverside package run `devtools::check()` and `devtools::build_site()`

## How to test
- [ ] Pull feat/distinct branch from molgenis/dsTidyverseClient
- [ ] Pull feat/distinct branch from molgenis/dsTidyverse
- [ ] Run: `devtools::load_all(path-to-clientside-package)`
- [ ] Start Armadillo on localhost
- [ ] Start xenon profile
- [ ] Install package on server:

```
devtools::build(path-to-serverside-package)
local_url <- "http://localhost:8080"
armadillo.login(local_url)
armadillo.install_packages(path-to-built-serverside-package, profile = "xenon")
```

- [ ] Upload test data:
```
data("mtcars")
armadillo.create_project("tidyverse")
armadillo.upload_table("tidyverse", "data", mtcars)
```

- [ ] Log in and assign data:
```
token <- armadillo.get_token(local_url)
builder <- newDSLoginBuilder()

builder$append(
  url = local_url,
  server = "cohort_1",
  token = token,
  driver = "ArmadilloDriver",
  profile = "xenon")

builder$append(
  url = local_url,
  server = "cohort_2",
  token = token,
  driver = "ArmadilloDriver",
  profile = "xenon")

builder$append(
  url = local_url,
  server = "cohort_3",
  token = token,
  driver = "ArmadilloDriver",
  profile = "xenon")

logindata <- builder$build()
conns <- datashield.login(logins = logindata, assign = FALSE)

datashield.assign(
  symbol = "mtcars",
  value = "tidyverse/data/mtcars",
  conns = conns)
```

- [ ] Run the test lines for `tests/testthat/test-distinct.R` Ignore the setting up a DSLite environment.

In addition:
- [ ] run `devtools::check()
- [ ] read vignette

2024-09-27 12:10 UTC, marikaris requested changes
Something went terribly wrong with your merge conflicts

2024-09-27 12:10 UTC, marikaris commented on docs/pkgdown.yml
> +<<<<<<< HEAD
This is not good

2024-09-27 12:10 UTC, marikaris commented on vignettes/dstidyverse.Rmd
> +<<<<<<< HEAD
What did you do?!

2024-09-27 12:55 UTC, marikaris commented
Also getting errors when running the first test:
`[1] "Bad request: No such DataSHIELD 'ASSIGN' method with name: distinctDS"`
I think it's because the missing comma's in `inst/DATASHIELD` in the ds-tidyverse repository

2024-09-30 08:58 UTC, timcadman commented
> Also getting errors when running the first test: `[1] "Bad request: No such DataSHIELD 'ASSIGN' method with name: distinctDS"` I think it's because the missing comma's in `inst/DATASHIELD` in the ds-tidyverse repository

I've fixed this in the serverside package

2024-10-03 09:08 UTC, marikaris approved these changes

2024-10-03 09:43 UTC, merged